### ISSUE TITLE
Include standard context: RDFa Core Initial Context

### ISSUE THREAD

**Issue by pietercolpaert** [pietercolpaert/rdfa-processor#1]
These prefixes should be automatically retrieved: https://www.w3.org/2013/json-ld-context/rdfa11

See spec: https://www.w3.org/2011/rdfa-context/rdfa-1.1

**Comment by csarven** [comment]
Acknowledging that fetching/including json-ld-context is convenient in the long run, note that json-ld-context is out of sync, and at least subject to be behind the (canonical) list in rdfa-context.
